### ISSUE TITLE
Problem med import htmlform

### ISSUE THREAD

**Issue by kesse** [martin-green/skojjt#20]
Hej,

För följande fel när jag deployar den senaste koden till google cloud

`Traceback (most recent call last):
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/hesse2u/default/main.py", line 8, in <module>
    import htmlform
ImportError: No module named htmlform`

Hur installerar jag htmlform?

**Comment by martin-green** [comment]
Fixat
