### ISSUE TITLE
TemplateNotFound: troops.html

### ISSUE THREAD

**Issue by kesse** [martin-green/skojjt#21]
Hej,

Verkar som filen troops.html inte har checkats in i samband med commit 324da7315276a02dae2cbac7ab6d88a2aef82662 4 december.

Får följande stacktrace när jag kör koden:

`
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/main.py", line 255, in start
    breadcrumbs=breadcrumbs)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/base/data/home/apps/e~gotalejon-narvaro/20170116t224124.398520058533917472/lib/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: troops.html`

**Comment by martin-green** [comment]
Fixat
